### PR TITLE
Add MyInfluxDbClient to DotNet clients

### PR DESCRIPTION
**Pull request by danielwertheim**
Add new .Net driver to list of .Net drivers.

### CODE REVIEW

**Comment by danielwertheim** [comment]
@beckettsean are there any issues with this PR?

Added here after guidance from you https://github.com/influxdb/influxdb.com/pull/549#issuecomment-164897720

**Comment by gunnaraasen** [comment]
@danielwertheim Thanks for contributing! Can you sign the [CLA](https://influxdb.com/community/cla.html)? Then we'll merge.

**Comment by danielwertheim** [comment]
I need to sign an agreement to contribute with a one-liner doc?

**Comment by beckettsean** [comment]
Thanks, @danielwertheim! Once you sign the [CLA](https://influxdb.com/community/cla.html) we can merge this

**Comment by beckettsean** [comment]
@danielwertheim it's a lawyer thing, don't expect rationality. Basically, if you make ANY contributions to our docs or source code without signing the CLA, then potentially in the future you could claim ownership of the copyright for that contribution, superceding whatever we have done with it since then.

Not that you would, or that it would work, but you could try. Thus, we ask you to sign the CLA. There's a very nice explanation at that link of why.

**Comment by danielwertheim** [comment]
@beckettsean done

**Comment by beckettsean** [comment]
CLA signed, merging.

**Pull request merged**
