### PR TITLE
Fix spelling of "GitHub"

### PR DESCRIPTION
**Pull request by splattael**
I used:

    perl -i -pe 's/Github/GitHub/g' `git grep -l Github`

### CODE REVIEW

**Comment by beckettsean** [comment]
Thanks, @splattael. We have to ask you to sign the [CLA](https://influxdb.com/community/cla.html) before we can merge.

**Comment by splattael** [comment]
@beckettsean Sure, done.

**Comment by beckettsean** [comment]
Thanks! Merging.

**Comment by splattael** [comment]
Thank you :)

**Pull request merged**
